.TH APP 1 "November 2024" "Version 1.0" "App Manual"

.SH NAME
App - консольное приложение для работы с котятами.

.SH SYNOPSIS
.B App
.RI [ add ]
.RI [ kill ]
.RI [ --help ]

.SH DESCRIPTION
Программа \fBApp\fP позволяет добавлять и удалять виртуальных "котиков", а также выводить информацию о текущем состоянии.

Команды:
.TP
\fBadd\fP
Добавить виртуального котика к текущей строке.

.TP
\fBkill\fP
Удалить всех виртуальных котиков из строки.

.TP
\fB--help\fP
Отобразить информацию о доступных командах и завершить работу программы.

.SH OPTIONS
Программа не принимает дополнительных опций командной строки.

.SH EXAMPLES
.B App add
.RS
Добавляет котика. Например:
.RS
^..^
.RE

.B App kill
.RS
Удаляет всех добавленных котиков.
.RE

.SH AUTHOR
Автор: Александр Магонов. Группа: ПО(б)-31. Программа разработана в рамках лабораторной работы.

.SH SEE ALSO
man(1)
